version: '3'

services:
  squid:
    image: sameersbn/squid:3.5.27-2
    restart: always
    ports:
      - "3128:3128"
    volumes:
      - ./squid.conf:/etc/squid/squid.conf
    environment:
      - SQUID_CACHE_DIR=/var/cache/squid